NumPy used for fast operation of an arrays, includes mathematical, logical , shape manipulation, sorting , selecting , basic linear algebra, statistical operations, random simulation.

NumPy arrays facilate advance mathematical operations on large numbers of data.

In [2]:
#import numpy
import numpy as np

In [3]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [4]:
type(x) #type of array

numpy.ndarray

In [5]:
x.ndim #dimension of array

1

In [6]:
x.shape #shape of array

(6,)

In [7]:
x.size #size of array

6

In [8]:
x.dtype #datatype of array

dtype('int32')

In [9]:
x[5]

6

In [10]:
x[:4] #view from array[0] to array[3] i.e upto 4th element

array([1, 2, 3, 4])

In [11]:
x[-1] #last element 

6

In [12]:
# Slicing of Array
x[2:5] # array elment from index 2 to 5

array([3, 4, 5])

In [13]:
# 2 Dimensional Array
arr = np.array( [ [1,2,3],[4,5,6] ] )
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# Shape of Array
arr.shape

(2, 3)

In [15]:
# Transpose of Array
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
# Array in 2 Dimension i.e row & column
myList =[[1,2,3],[4,5,6],[7,8,9]]
myList


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(myList)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# Range Function 
np.arange(0, 10) # Number between 0 to 10 i.e 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,11,2) # Number between 0 to 11 with step size 2 

array([ 0,  2,  4,  6,  8, 10])

In [21]:
np.zeros((4)) # ! Dimensional array with all zeros

array([0., 0., 0., 0.])

In [24]:
np.zeros((4,4)) # Multi-dimensional array with all zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((4)) # ! Dimensional array with all ones

array([1., 1., 1., 1.])

In [22]:
np.ones((4,4)) # MUlti-dimensional array with all ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
# Axis 
# Axis = 1 for row & Axis = 0 for column
A = np.array([ [1,2,3,4],[5,6,7,8] ])  #This Is A 2D Array
A.sum(axis = 1)  # Sum of row element
                         

array([10, 26])

In [32]:
A.sum(axis = 0)

array([ 6,  8, 10, 12])

In [39]:
x =np.array([[1,2],[3,4]])
y =np.array([[3,4],[4,5]])
x + y # Addition of two array

array([[4, 6],
       [7, 9]])

In [ ]:
# Dot Product 
np.dot(x,y)

In [38]:
# Cross Product
np.cross(x,y)

array([-2, -1])

In [41]:
# Sorting
x =np.array([[23,1,345,2,576,234,14], [11,34,253,256,21,67,72]])
np.sort(x, axis = 1) # Row wise sorting
#np.sort(x)


array([[  1,   2,  14,  23, 234, 345, 576],
       [ 11,  21,  34,  67,  72, 253, 256]])

In [42]:
np.sort(x, axis = 0) # Column wise sorting

array([[ 11,   1, 253,   2,  21,  67,  14],
       [ 23,  34, 345, 256, 576, 234,  72]])

In [43]:
np.sort(x, kind = 'mergesort') # Merge sort divide the array into half & then compare & sort at correct position

array([[  1,   2,  14,  23, 234, 345, 576],
       [ 11,  21,  34,  67,  72, 253, 256]])

In [44]:
np.sort(x, kind = 'quicksort') # Quicksort take a pivot element, compare with that pivot & then sort at correct position

array([[  1,   2,  14,  23, 234, 345, 576],
       [ 11,  21,  34,  67,  72, 253, 256]])

In [45]:
# Reshape
# Reshape change 1 D array into 2 D array 
b=np.array([56, 78, 34, 67, 34, 56, 23, 54, 36])
b = b.reshape(3,3)
b

array([[56, 78, 34],
       [67, 34, 56],
       [23, 54, 36]])